#!/bin/bash
# Compiles an art program to an executable

# Path to ART compiler
if [ -e "./art.native" ]
then
    ART="./art.native"
elif [ -e "./art" ]
then
    ART="./art"
else
    echo "No art compiler found. Attempting build..."
    echo ""
    make clean
    if make 
    then
        ART="./art.native"
    else
        echo -e "\nBuild Failed!!!" && exit 2
    fi
fi



base=`echo $1 | sed 's/.*\\///
                             s/.art//'`

if [ -z $2 ]
then 
    out=./$base
else
    out=$2
fi

${ART} < $1 > /tmp/${base}.bc &&
llc /tmp/${base}.bc &&
gcc /tmp/${base}.s -o ${out}

